services:

  devcontainer:
    build:
      context: .  
      dockerfile: dockerfile

    volumes:
      # Mount one directory up to the container's repo folder.
      - ../:/repo

    command: sleep infinity 
    platform: linux/amd64