services:

  devcontainer:
    build:
      context: .  
      dockerfile: dockerfile
    image: devcontainer:latest

    volumes:
      # Mount one directory up to the container's repo folder.
      - ../:/repo

    command: sleep infinity 
    platform: linux/amd64